# Generated by Django 5.0.6 on 2024-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo_count', models.IntegerField()),
                ('information', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
